#%RAML 1.0
title: cryptdecryptmule
version: 1.0.0
types:
  error: !include DataType/error.raml

/:
 get:
   description: "return home page"
   displayName: "Home"
   protocols:
     - HTTP
   responses:
     